### ISSUE TITLE
Issue with geometries coming from Facilities Database

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-cpdb#114]
156 records in CPDB have a point geometry from the Facilities Database, but the point is not in or near NYC.  See screenshots that explain diagnosis. 
![Screen Shot 2022-06-08 at 11 44 37 AM](https://user-images.githubusercontent.com/5611960/172660072-6f32a12c-98bf-4403-ab48-78dcda28e7a1.png)

![Screen Shot 2022-06-08 at 11 45 23 AM](https://user-images.githubusercontent.com/5611960/172660232-378a837b-f98b-4f25-b3f2-e37886ebc5d3.png)
No points are in NYC

![Screen Shot 2022-06-08 at 11 45 49 AM](https://user-images.githubusercontent.com/5611960/172660356-051fbfbe-3b41-44d5-ba8e-5bbcf68c86e3.png)
And the Lat and Long values are incorrect.

Perhaps the projection of the Facilities Database needs to be updated when loading into data libraries?  Or?

**Comment by td928** [comment]
Issue closed because a new source crs is assigned and now facilities are corrected in CPDB confirmed by looking at pts output in the most recent batch.
