### ISSUE TITLE
Move CPDB from the private folder in DO to a public folder (edm-publishing) 

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-cpdb#125]
Currently, CPDB is hosted on DO in a private folder but AD wants us to explore how we can move CPDB from a private to public folder on DO akin to our other data products that are now available to the public. 

Look for where `cpdb` and the `edm-private` bucket are referenced and update by repo. 

Will keep this ticket in `db-cpdb` but open individual issues for each repo:

**CPDB**
Update script to upload to the path that we decide to store cpdb upload 
- [x] cpdb.sh (`cpdb_upload` + `share`) https://github.com/NYCPlanning/db-https://github.com/NYCPlanning/db-cpdb/blob/8d87841a6dc3084079e985456175b5f78ffd49f5/cpdb.sh#L40-L67

**data-engineering-qaqc**
QAQC app reads from edm-private 
- [ ] `src/cpdb/helpers.py` `(BUCKET-NAME`) https://github.com/NYCPlanning/data-engineering-qaqc/blob/4fa0fcd30a80cd1c0a2c11b818b1def54632bf46/src/cpdb/helpers.py#L9

Additional information about edm-private bucket:

@SashaWeinstein pointed out that the edm-private bucket is also mentioned in a few other repo's not related to CPDB:

**db-melissa**
https://github.com/NYCPlanning/db-melissa/blob/19337573874f05af78d70ac4289e8f2d682b8076/melissa.sh

**dob_now_permits**
https://github.com/NYCPlanning/db-data-library/blob/f87a8de01bf3c5e757c44f8460c7fdca7840fc76/library/script/dob_now_permits.py

**dob_now_applications**
https://github.com/NYCPlanning/db-data-library/blob/f87a8de01bf3c5e757c44f8460c7fdca7840fc76/library/script/dob_now_applications.py

**Comment by AmandaDoyle** [comment]
@mbh329  can you cross reference your notes with Sasha's, which I think are in Teams, and verify that they align, and if not what's different?

**Comment by mbh329** [comment]
Yes, these align with the notes Sasha took. I am not seeing any PR's that @SashaWeinstein opened

**Comment by mbh329** [comment]
I will touch base with Sasha tomorrow and open up the necessary PR's to make this change across the necessary repos
