### ISSUE TITLE
Incorporate manual geometries from Capital Planning

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-cpdb#21]
The attached file has additional manually mapped geometries from Capital Planning to incorporate into CPDB.  These would be added on in the same place where other "AD Sprint" projects are incorporated
[CPDB_Dec20_UpdateFile_EDCgeoms.csv.zip](https://github.com/NYCPlanning/db-cpdb/files/5748364/CPDB_Dec20_UpdateFile_EDCgeoms.csv.zip)

**Comment by mgraber** [comment]
This is still outstanding. See this error:
https://github.com/NYCPlanning/db-cpdb/runs/1623403323?check_suite_focus=true#step:6:7286
