### ISSUE TITLE
Incorporate EP 2020 manual geoms into CPDB

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-cpdb#50]
[cpdb_dec20_updatefile_edcgeoms_v2.zip](https://github.com/NYCPlanning/db-cpdb/files/5788836/cpdb_dec20_updatefile_edcgeoms_v2.zip)
Incorporate EP 2020 manual geoms into CPDB.  To replace old EP 2020 file

**Comment by mgraber** [comment]
@AmandaDoyle We'd need to export this as a csv to keep the same workflow:

[edcgeoms_2021-01-08.csv.zip](https://github.com/NYCPlanning/db-cpdb/files/5789082/edcgeoms_2021-01-08.csv.zip)
