### ISSUE TITLE
Missing spatial data for DOT and DDC in latest version

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-cpdb#74]
Fewer records are mapped for DOT and DDC 
geomsource column in the dcpattributes files had 434 projects in the Jan plan poly file mapped from ddc, and that's down to 0 in this latest file.

**Comment by AmandaDoyle** [comment]
@SPTKL @mgraber 
DDC spatial data includes two shapefiles: infrastructure and public buildings 
It looks like the infrastructure dataset got loaded into digital ocean for both infrastructure and public buildings input datasets, and the infrastructure projects are being [overwritten](https://github.com/NYCPlanning/db-cpdb/blob/c72bf3069f43bc393d12a82908ca5f9b281f336a/sql/attributes_ddc.sql#L17) with the centroid of the infrastructure project, instead of the centroid of the public building, which is why there are no ddc records in the polygon file

**Comment by mgraber** [comment]
@AmandaDoyle @SPTKL When loading the DDC data to spatial library from local, we might need to manually rearrange the two shapefiles into their own directories rather than relying on subpaths.

**Comment by AmandaDoyle** [comment]
There's something going on for the spatial data for DOT records but I can't pinpoint it, nor can I verify that it's limited to DOT spatial data.

Here's what I've found so far
- If I run each of the components in [this script](https://github.com/NYCPlanning/db-cpdb/blob/c72bf3069f43bc393d12a82908ca5f9b281f336a/sql/attributes_dot.sql#L1) I'd expect 71 records to have a geometry from `dot_projects_intersections`, 105 to have a a geometry from `dot_projects_streets`, and 206 from `dot_projects_bridges_byfms`, but some of the records in the `cpdb_dcpattributes` that have a matching `maprojid` in a DOT table have a NULL geometry.  It's understandable if things get overwritten downstream (i.e. DDC or DPR can overwrite DOT), but a record should not have a NULL geometry.  The record with NULL geometries have a managing agency code of (801 = SBS, 826 = DEP, 850 = DDC)

**Comment by AmandaDoyle** [comment]
```
WITH proj AS (
SELECT ST_Multi(ST_Union(wkb_geometry)) as geom,
       fmsagencyid||fmsid as fmsid
FROM dot_projects_streets
GROUP BY fmsagencyid, fmsid
)
SELECT DISTINCT magency FROM cpdb_dcpattributes WHERE maprojid IN (
SELECT DISTINCT maprojid
FROM proj a, cpdb_projects b
WHERE b.maprojid = a.fmsid)
AND geom IS NULL;
```

That the core script I used.  You can swap out dot_projects_streets for dot_projects_intersections

**Comment by SPTKL** [comment]
```sql
SELECT a.*, b.geom
FROM cpdb_dcpattributes a, (
	SELECT ST_Multi(ST_Union(wkb_geometry)) as geom,
	       fmsagencyid||fmsid as fmsid
	FROM dot_projects_streets
	GROUP BY fmsagencyid, fmsid
) b
where a.geom is null and 
maprojid in (
	SELECT fmsagencyid||fmsid as fmsid FROM dot_projects_streets
)
and a.maprojid = b.fmsid
```

**Comment by mgraber** [comment]
@AmandaDoyle 
They are getting NULLed in the bad geoms step:
https://github.com/NYCPlanning/db-cpdb/blob/bfc5d676f9e1cf9d57b0ac2c6b42aedb0f4ef0d3/sql/attributes_badgeoms.sql#L16-L26

You can try running this in EDM data:
```sql
WITH bad_geoms AS(
	SELECT DISTINCT maprojid
	FROM cpdb.dcp_cpdb_agencyverified
	WHERE (mappable = 'No - Can be in future'
	OR mappable = 'No - Can never be mapped')
)
SELECT a.*, 
		b.geom,
		(a.maprojid IN (SELECT maprojid FROM bad_geoms)) as bad_geoms
FROM cpdb.cpdb_dcpattributes a, (
	SELECT ST_Multi(ST_Union(wkb_geometry)) as geom,
	       fmsagencyid||fmsid as fmsid
	FROM cpdb.dot_projects_streets
	GROUP BY fmsagencyid, fmsid
) b
where a.geom is null and 
maprojid in (
	SELECT fmsagencyid||fmsid as fmsid FROM cpdb.dot_projects_streets
)
and a.maprojid = b.fmsid;
```

**Comment by AmandaDoyle** [comment]
AD Notes from review:
Using the scripts below these are the number of projects that get a match with the various DOT sources
dot_projects_bridges_byfms 103
dot_projects_intersections 71
dot_projects_streets 105

```
SELECT b.*
FROM cpdb.dot_projects_bridges_byfms as a, cpdb.cpdb_dcpattributes b
WHERE b.maprojid = regexp_replace(a.fms_id,' ','');

WITH proj AS (
SELECT ST_Multi(ST_Union(wkb_geometry)) as geom,
       fmsagencyid||fmsid as fmsid
FROM cpdb.dot_projects_intersections
GROUP BY fmsagencyid, fmsid
)
SELECT b.*
FROM proj as a, cpdb.cpdb_dcpattributes b
WHERE b.maprojid = a.fmsid;

WITH proj AS (
SELECT ST_Multi(ST_Union(wkb_geometry)) as geom,
       fmsagencyid||fmsid as fmsid
FROM cpdb.dot_projects_streets
GROUP BY fmsagencyid, fmsid
)
SELECT b.*
FROM proj as a, cpdb.cpdb_dcpattributes b
WHERE b.maprojid = a.fmsid;
```

But in the output there is the following count

dot_projects_bridges	96
dot_projects_intersections	13
dot_projects_streets	96

```
SELECT dataname, COUNT(*) FROM cpdb.cpdb_dcpattributes
GROUP BY dataname;
```

Why?
Records that initially had a match with a DOT source, may have been overwritten by a downstream source.  This is especially true for `dot_projects_streets` which is overwriting geometries  that initially matched with `intersections`.

Even though there are 279 matches, there are only 215 distinct maprojids.

There are 14 maprojids that have a NULL geom, and these 14 records are having their geom set to NULL in [this part](https://github.com/NYCPlanning/db-cpdb/blob/bfc5d676f9e1cf9d57b0ac2c6b42aedb0f4ef0d3/sql/attributes_badgeoms.sql#L16) of the badgeom script.

```
WITH bridges as (SELECT b.*, 'bridges' as init
FROM cpdb.dot_projects_bridges_byfms as a, cpdb.cpdb_dcpattributes b
WHERE b.maprojid = regexp_replace(a.fms_id,' ','')),
intersections as (
SELECT b.*, 'intersections' as init
FROM cpdb.cpdb_dcpattributes b, (SELECT ST_Multi(ST_Union(wkb_geometry)) as geom,
       fmsagencyid||fmsid as fmsid
FROM cpdb.dot_projects_intersections
GROUP BY fmsagencyid, fmsid) as a
WHERE b.maprojid = a.fmsid),
streets as (
SELECT b.*, 'streets' as init
FROM cpdb.cpdb_dcpattributes b, (SELECT ST_Multi(ST_Union(wkb_geometry)) as geom,
       fmsagencyid||fmsid as fmsid
FROM cpdb.dot_projects_streets
GROUP BY fmsagencyid, fmsid) as a
WHERE b.maprojid = a.fmsid),
collapsed as (
SELECT * FROM bridges
UNION
SELECT * FROM intersections
UNION 
SELECT * FROM streets)
SELECT DISTINCT maprojid FROM collapsed WHERE geom is NULL and maprojid IN
(SELECT DISTINCT maprojid
FROM cpdb.dcp_cpdb_agencyverified
WHERE (mappable = 'No - Can be in future'
OR mappable = 'No - Can never be mapped'));
```

**Comment by AmandaDoyle** [comment]
Update the logic of [this code snippet](https://github.com/NYCPlanning/db-cpdb/blob/bfc5d676f9e1cf9d57b0ac2c6b42aedb0f4ef0d3/sql/attributes_badgeoms.sql#L16) so that it's the following:
Set the geometry of the project to NULL if
the project is in the `dcp_cpdb_agencyverified` table
AND `mappable = 'No - Can never be mapped'`
OR (`mappable = 'No - Can be in future AND (geomsource <> 'dpr' OR geomsource <> 'dot' OR geomsource <> 'ddc' OR geomsource <> 'edc' ))

Should [this logic](https://github.com/NYCPlanning/db-cpdb/blob/bfc5d676f9e1cf9d57b0ac2c6b42aedb0f4ef0d3/sql/attributes_badgeoms.sql#L13) be updated to include

**Comment by epramik** [comment]
> Update the logic of [this code snippet](https://github.com/NYCPlanning/db-cpdb/blob/bfc5d676f9e1cf9d57b0ac2c6b42aedb0f4ef0d3/sql/attributes_badgeoms.sql#L16) so that it's the following:
> Set the geometry of the project to NULL if
> the project is in the `dcp_cpdb_agencyverified` table
> AND `mappable = 'No - Can never be mapped'`
> OR (`mappable = 'No - Can be in future AND (geomsource <> 'dpr' OR geomsource <> 'dot' OR geomsource <> 'ddc' OR geomsource <> 'edc' ))
> 
> Should [this logic](https://github.com/NYCPlanning/db-cpdb/blob/bfc5d676f9e1cf9d57b0ac2c6b42aedb0f4ef0d3/sql/attributes_badgeoms.sql#L13) be updated to include EDC as well?

This looks good to me, and please add edc to line 13 as well.
