### ISSUE TITLE
Change `SBS` to `EDC` for all sponsor and managing agency info

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-cpdb#84]
Change `SBS` to `EDC` for all sponsor and managing agency info

**Comment by LubaPlanning** [comment]
SBS Projects with "Governors Island" in the description should have the following changes:
-magencyname should be "Trust for Governors Island"
-magencyacro and sagencyacro should be "TGI"

SBS Projects with "BNY" in the description should have the following changes:
-magencyname should be "Brooklyn Navy Yard"
-magencyacro and sagencyacro should be "BNY"

All other SBS projects should change to read:
-magencyname should be "Economic Development Corporation"
-magencyacro and sagencyacro should be "EDC"

Do not change magency for any of the above (for now, anyway)
