### ISSUE TITLE
Point and Polygon outputs are empty

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-cpdb#94]
Outputs `cpdb_dcpattributes_poly` and `cpdb_dcpattributes_pts` are empty.
No records are getting written into output because of this [filter](https://github.com/NYCPlanning/db-cpdb/blob/af012bab9c612385464cf1d770682121fbc78000/sql/_create_export.sql#L4) in the export step
Update [version.env](https://github.com/NYCPlanning/db-cpdb/blob/b5848c096183b081139350a3085c4b2408f5282a/version.env) file to fisa_2022

**Comment by td928** [comment]
the other place I see different ccp might come in is omb_capitalcommitments . But I did a look around it seems this table is not loaded in the first step. Is this something already depreciated? If fisa_2022 seems to be only value for `ccpversion`
